### ISSUE TITLE
nil is not a valid asset source

### ISSUE THREAD

**Issue by casiodk** [zooppa/administrate-field-carrierwave#8]
Hi. Is it possible to avoid this error when the image source for some reason is nil

Maybe in options {
  allow_nil: true
}

and then check for the asset source before rendering the image_tag

https://stackoverflow.com/questions/37530024/rails-5-nil-is-not-a-valid-asset-source-using-carrierwave/38567519

**Comment by GeoffAbtion** [comment]
This was fixed by https://github.com/zooppa/administrate-field-carrierwave/pull/7 and released as part of 0.3.1 (and later versions)

Update your  `administrate-field-carrierwave` gem version.
